#ifndef MINILANG_LEXER_HPP
#define MINILANG_LEXER_HPP

#include <cstdio>

#include "minilang/source_location.hpp"

// C-style interface exported by the Flex-generated scanner
// (src/lexer/lexer.l). The driver and, later, the Bison parser consume
// tokens exclusively through this header.

// Returns the next token kind (codes are generated by Bison into
// parser.tab.hpp), or 0 at end of input. Side effects: fills the
// parser-owned yylval/yylloc and ml_token_loc with the token's start
// position.
extern int yylex();

// Flex-provided globals: the raw lexeme of the current token.
extern char* yytext;
extern int   yyleng;

namespace minilang {

// Start position (line, column) of the most recently returned token.
extern SourceLocation ml_token_loc;

// Resets the scanner onto a fresh input stream and restarts line/column
// counting at 1:1. Must be called once before the first yylex().
void lexerInit(std::FILE* input);

// Human-readable name for a token kind, e.g. "KEYWORD_INT", "IDENTIFIER".
// Used by the --tokens dump and by diagnostics.
const char* tokenName(int kind);

} // namespace minilang

#endif // MINILANG_LEXER_HPP
